### ISSUE TITLE
Test INNUca Pipeline and check the outputs

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps#21]

**Comment by karinlag** [comment]
See #1

**Comment by ajkarloss** [comment]
One of the tools used in EFSA pipeline for QC is trueCoverage.py in INNUca Pipeline for "calcualting coverage and contamination check". I am trying to understand and install locally. 

There are few issuses here: 
1. Developed using Python2 (not supoorted since 2020 Jan 1st)
2. But the dependency tools (ReMatch ....) needs python 3.0+. Not possible to install in a single conda env. It complicates installation and updating 
3. needs species name as input and also the expected read length, etc as input
4. Tools have not been updated since 2019
5. Some of the issues are not answered 
6. As far as we know, the team which developed has left and not working/maintaining on it any more. Not possible to expect any help or development. We risk of "redeveloping" the pipeline very soon. 

For me, it looks like we should not use this tool even though EFSA uses. EFSA will (should) move away from it sooner.

**Comment by ajkarloss** [comment]
We had long discusssions and agreed on following things: 
1. We need only the general basic coverage (at least for the current iteration). 
2. Intraspecies contamination can/will be added to Assembly_QC in next iteration. 

So, we close this issue
