### ISSUE TITLE
Written documentation on port 8080 on NREC

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/IRIDA_Plugin_Development_Steps#5]

**Comment by karinlag** [comment]
Hi @georgemarselis-nvi !

I wondered if you could prioritize this one on Monday. I have a LIMS update meeting at 1400 on the 26th of Sept, and would like to explain better why we have issues. 

Also, I am a bit confused: 8080 is not on the blocked list that is published by nrec. What am I misunderstanding?

https://docs.nrec.no/acl.html

**Comment by georgemarselis-nvi** [comment]
https://docs.nrec.no/acl.html

NREC this past summer, in order to increase security, has further blocked access to non-"popular" ports or established ports used by web services, meaning, they have restricted access to ports ports other than 80 (HTTP) and 443 (HTTPS) for web services.

Specifically, in the section that mentions:

![image](https://user-images.githubusercontent.com/77984068/192258347-188f8f51-5f28-4d8b-916a-fb818d23841c.png)

"The following ports are blocked, except from Norwegian universities and colleges."

Tomcat (IRIDA) and Galaxy use port 8080 right now, because 

1. it was the easiest thing to do
2. There an on-going discussion about certificates
3. lack of time to move to from 8080 to 80 and 443
4.  a bunch of work in order to redirect incoming ports.

**What this means, effectively, is that unless you are with the NVI network (Building or VPN), you cannot access VIGASP.**

Furthermore, there are two distinct problems:

1. Not all NVI laptops that run Windows have this AlwaysOnVPN mechanism that makes the laptop seem as if it is a part of the NVI network all the time. IT has told me that they are working on the transision
2. IT security has not thought yet a way for non-Windows users (specifically Linux and the spare Mac we have) to access the NVI network with VPN. So anybody that has linux and requires a graphical browser to connect to VIGASP, is in the same boat as the Windows users without AlwaysOnVPN

**Comment by Camilsek** [comment]
Thanks for this update. 
How much work is it to move VIGAS-P to port 80 or 443? And will this be possible to do?

**Comment by georgemarselis-nvi** [comment]
Significant and i was not planning on doing it before mid-january, where all of you are too busy with grants (and therefore cannot use VIGASP)

There is:

  1.  reading and learning about certificates in Galaxy and Apache Tomcat
  2.  Discussion within IT about acquiring host-specific certificates
     *   probably automated renewal, but I cannot guarantee that, it will have to be discussed internally within IT and see all the possibilities
  3.  Documented issues in a previous conversation about part of the software not starting by itself after reboot, when moved out of 8080
  4.  Testing to see if altering the port destroys the existing metadata (sequenced sample files upload uploaded, when and where they are located on disk)


Best Regards,

----

George Marselis

Linux Engineer

HPC and Bioinformatics @NVI

________________________________

**Comment by Camilsek** [comment]
ok, thank you George. Let's discuss this in the meeting later today and decided whether we close this issue now or continue working with it.
I would very much like to have @karinlag to have a look at this as well.

**Comment by karinlag** [comment]
Figuring this out is different that figuring out what is going on. Closing, setting up new issue.
